### ISSUE TITLE
no such class as org.bukkit.craftbukkit.CraftWorld

### ISSUE THREAD

**Issue by KeineSecrets** [yannicklamprecht/WorldBorderAPI#119]
**Describe the bug**
When I import the latest API into my project, there's no such class as org.bukkit.craftbukkit.CraftWorld
I'm using Paper 1.20.2

**To Reproduce**
1. Implement into Project
2. Code anything using the API
3. Build and restart the server

**Expected behavior**
Should just work fine

**Screenshots**
`[14:03:41] [Server thread/WARN]: [SkyBlock] Task #21 for SkyBlock v1.0 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R3/CraftWorld
    at com.github.yannicklamprecht.worldborder.impl.WorldBorder.<init>(WorldBorder.java:26) ~[?:?]
    at com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.getWorldBorder(WorldBorderApiImpl.java:27) ~[?:?]
    at com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.setBorder(WorldBorderApiImpl.java:57) ~[?:?]
    at com.github.yannicklamprecht.worldborder.plugin.PersistenceWrapper.setBorder(PersistenceWrapper.java:73) ~[?:?]
    at com.github.yannicklamprecht.worldborder.plugin.PersistenceWrapper.setBorder(PersistenceWrapper.java:68) ~[?:?]
    at net.playodyssey.island.IslandManager.spawnOrReloadBorder(IslandManager.java:121) ~[?:?]
    at net.playodyssey.command.IslandCommand.lambda$create$0(IslandCommand.java:42) ~[?:?]
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1256) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R3.CraftWorld
    ... 15 more`

**Comment by yannicklamprecht** [comment]
You're using the 1.20.3/4 compatible version on 1.20.1. Download version https://github.com/yannicklamprecht/WorldBorderAPI/releases/tag/1.201.0 instead.

**Comment by KeineSecrets** [comment]
Thank you so much!
