### ISSUE TITLE
Error java.io.FileNotFoundException: Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by johncsuti** [yannicklamprecht/WorldBorderAPI#21]
**Describe the bug**
Plugin doesn't load complaining there is no plugin.yml

**To Reproduce**
Not sure just install api 1.0.5 on a 1.14.4 paper server

**Expected behavior**
It loads so bentobox can hook into the api and use it

**Screenshots**
N/A

**Additional context**
[18:23:37 ERROR]: Could not load 'plugins/API(1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:142) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-233]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by yannicklamprecht** [comment]
Use 1.0.4 release. 1.0.5 was only to test deployment of the API and the Testplugin into the GitHub Releases section.
