### ISSUE TITLE
Cannot use the library in a plugin?

### ISSUE THREAD

**Issue by SharpBit** [yannicklamprecht/WorldBorderAPI#27]
I'm trying to use the world border api in my plugin but i get this when i run the command that uses it:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'tag' in plugin UltimateTag v1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:690) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1606) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1460) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:36) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:876) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:869) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:853) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:793) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/github/yannicklamprecht/worldborder/api/BorderAPI
	at me.sharpbit.ultimatetag.commands.TagCommand.onCommand(TagCommand.java:49) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.github.yannicklamprecht.worldborder.api.BorderAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at me.sharpbit.ultimatetag.commands.TagCommand.onCommand(TagCommand.java:49) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
	... 17 more
```
It says this: `Caused by: java.lang.NoClassDefFoundError: com/github/yannicklamprecht/worldborder/api/BorderAPI`

In Eclipse, before exporting my plugin as a jar, I added the API.jar file as a referenced library from an external jar. There are no errors when exporting as a jar. What's going on and how do I fix this? Also your docs (README.md) say `WorldBorderAPI` but eclipse says the jar only has `WorldBorderApi` (not all caps for API)

Here's my code:
```java
		@SuppressWarnings("unchecked")
		List<Player> players = (List<Player>) Bukkit.getOnlinePlayers();
		World world = player.getWorld();
		
		WorldBorderApi wb = BorderAPI.getApi();
		Random rand = new Random();
		int x = rand.nextInt(5000) - 2500;
		int z = rand.nextInt(5000) - 2500;
		
		// Teleport players, set world border, and update inventories and health
		players.get(0).teleport(getHighestY(world, x - 49, z - 49));
		players.get(1).teleport(getHighestY(world, x + 49, z + 49));
		
		for (Player p: players) {
			PlayerInventory inv = p.getInventory();
			inv.clear();
			inv.setItem(0, new ItemStack(Material.DIAMOND_AXE, 1));
			inv.setItem(1, new ItemStack(Material.DIAMOND_PICKAXE, 1));
			inv.setItem(2, new ItemStack(Material.DIAMOND_SHOVEL, 1));
			inv.setItem(3, new ItemStack(Material.COBBLESTONE, 16));
			
			if (p.getName().equals(player.getName())) {
				inv.setItem(8, new ItemStack(Material.COMPASS, 1));
			}
			
			p.setHealth(20);
			p.setFoodLevel(20);
			
			wb.setBorder(p, 50, new Location(player.getWorld(), x, 70, z));
		}
```

**Comment by yannicklamprecht** [comment]
Do you have https://github.com/yannicklamprecht/WorldBorderAPI/releases/download/1.152.1/WorldBorderPlugin-1.152.1-SNAPSHOT.jar as a plugin in your plugins folder?

**Comment by SharpBit** [comment]
No, do I need that to use the API?

**Comment by yannicklamprecht** [comment]
Sure for testing it on the server you need the implementation as well. See https://github.com/yannicklamprecht/WorldBorderAPI#usage
