### ISSUE TITLE
Exception NoSuchMethodError whilst calling CraftWorld.getHandle()

### ISSUE THREAD

**Issue by Tsuser1** [yannicklamprecht/WorldBorderAPI#80]
**Describe the bug**
NoSuchMethodError exception occurring while attempting to initialize API.

**Stack Trace**
```
java.lang.NoSuchMethodError: 'net.minecraft.server.level.ServerLevel org.bukkit.craftbukkit.v1_18_R2.CraftWorld.getHandle()'
        at com.github.yannicklamprecht.worldborder.impl.WorldBorder.<init>(WorldBorder.java:30) ~[worldborderapi-1.182.0-dev.jar:?]
        at com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.getWorldBorder(WorldBorderApiImpl.java:32) ~[worldborderapi-1.182.0-dev.jar:?]
        at com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.resetWorldBorderToGlobal(WorldBorderApiImpl.java:37) ~[worldborderapi-1.182.0-dev.jar:?]
        at com.github.yannicklamprecht.worldborder.plugin.PersistenceWrapper.resetWorldBorderToGlobal(PersistenceWrapper.java:48) ~[worldborderapi-1.182.0-dev.jar:?]
        at world.bentobox.border.listeners.ShowWorldBorder.showBorder(ShowWorldBorder.java:41) ~[?:?]
        at world.bentobox.border.listeners.PlayerListener.lambda$onPlayerJoin$0(PlayerListener.java:51) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at world.bentobox.border.listeners.PlayerListener.lambda$onPlayerJoin$1(PlayerListener.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Environment**
 - Server runtime: `git-Paper-317 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e5da93a)` (latest)
 - BentoBox version: `1.20.1` (latest)
 - Border addon version: `3.2.0` (latest)

**Comment by yannicklamprecht** [comment]
Wrong jar. you need the non dev version. https://github.com/yannicklamprecht/WorldBorderAPI/releases/download/1.182.0/worldborderapi-1.182.0.jar
