### ISSUE TITLE
Error - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by HannahPhillipsR** [yannicklamprecht/WorldBorderAPI#81]
**Describe the bug**
While using paper, console being spammed by an error message that says "

java.lang.NoSuchMethodError: 'net.minecraft.server.level.ServerLevel org.bukkit.craftbukkit.v1_18_R2.CraftWorld.getHandle()'
    at worldborderapi-1.182.0-dev.jar//com.github.yannicklamprecht.worldborder.impl.WorldBorder.<init>(WorldBorder.java:30)
    at worldborderapi-1.182.0-dev.jar//com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.getWorldBorder(WorldBorderApiImpl.java:32)
    at worldborderapi-1.182.0-dev.jar//com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.resetWorldBorderToGlobal(WorldBorderApiImpl.java:37)
    at worldborderapi-1.182.0-dev.jar//com.github.yannicklamprecht.worldborder.plugin.PersistenceWrapper.resetWorldBorderToGlobal(PersistenceWrapper.java:48)
    

**To Reproduce**
1. Go to the console
2. See an error

**Expected behavior**
Not for the console to be spammed by the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/42947632/167300043-515943c0-21aa-4f4b-a282-1e0e446e7341.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 101.0.4951.54 (Official Build) (64-bit)

**Additional context**
This server is running Paper version git-Paper-328 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 87d2eb2)
Previous version: git-Paper-317 (MC: 1.18.2)

**Comment by yannicklamprecht** [comment]
https://github.com/yannicklamprecht/WorldBorderAPI/issues/80#issuecomment-1117657080
