### ISSUE TITLE
java.lang.NoSuchFieldError: world for arclight bukkit 

### ISSUE THREAD

**Issue by aaa8881** [yannicklamprecht/WorldBorderAPI#89]
Java 11 , Arclight (modded plugin bukkit, mixing from spigot ) 1.16.5 

API works fine with vanilla spigot bukkit. issue caused by arclight. unsure if this can be fixed from WorldborderAPI side. 

Log and code snippet attached below. 

```
java.lang.NoSuchFieldError: world
        at com.github.yannicklamprecht.worldborder.v1_16_R3.WorldBorder.<init>(WorldBorder.java:20) ~[WorldBorderPlugin-1.165.0%20(1).jar:?] {re:classloading}
        at com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.getWorldBorder(WorldBorderApiImpl.java:27) ~[WorldBorderPlugin-1.165.0%20(1).jar:?] {re:classloading}
        at com.github.yannicklamprecht.worldborder.api.WorldBorderApiImpl.setBorder(WorldBorderApiImpl.java:57) ~[WorldBorderPlugin-1.165.0%20(1).jar:?] {re:classloading}
        at com.github.yannicklamprecht.worldborder.plugin.PersistenceWrapper.setBorder(PersistenceWrapper.java:69) ~[WorldBorderPlugin-1.165.0%20(1).jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.github.yannicklamprecht.worldborder.plugin.PersistenceWrapper.setBorder(PersistenceWrapper.java:64) ~[WorldBorderPlugin-1.165.0%20(1).jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.signition.samcore.module.IslandManager.showBorder(IslandManager.java:40) ~[SamCoreLatest.jar:?] {re:classloading}
        at com.signition.samcore.module.IslandManager$1.run(IslandManager.java:53) ~[SamCoreLatest.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.24-SNAPSHOT-aa5299f] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:400) ~[arclight:arclight-1.16.5-1.0.24-SNAPSHOT-aa5299f] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.handler$bae000$arclight$runScheduler(MinecraftServerMixin.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
`

Corresponding code is real simple, but attaching anyways. 

```
        WorldBorderApi api = BorderAPI.getApi();
        api.setBorder(player, protectionSize , center);
```

**Comment by yannicklamprecht** [comment]
Modded servers are not supported.
